include ../../global_config

OBJS =  $(OBJDIR)/bluebanana.o
OBJS += $(OBJDIR)/bluebananaconfig.o
OBJS += $(OBJDIR)/bluebananaslider.o
OBJS += $(OBJDIR)/bluebananawindow.o
OBJS += $(OBJDIR)/bluebananalookups.o
OBJS += $(OBJDIR)/bluebananaengine.o

OUTPUT = $(PLUGIN_DIR)/bluebanana.plugin

include ../../plugin_config

$(OBJDIR)/bluebanana.o:			bluebanana.C
$(OBJDIR)/bluebananaconfig.o:		bluebananaconfig.C
$(OBJDIR)/bluebananaslider.o:		bluebananaslider.C
$(OBJDIR)/bluebananawindow.o:		bluebananawindow.C
$(OBJDIR)/bluebananalookups.o:		bluebananalookups.C
$(OBJDIR)/bluebananaengine.o:		bluebananaengine.C

