include ../../global_config

OBJS = $(OBJDIR)/deinterlace-cv.o  \
	$(OBJDIR)/deinterwindow-cv.o

OUTPUT = $(PLUGIN_DIR)/deinterlace-cv.plugin

include ../../plugin_config

$(OBJDIR)/deinterlace-cv.o: deinterlace-cv.C
$(OBJDIR)/deinterwindow-cv.o: deinterwindow-cv.C



